### PR TITLE
Fix struct typedef declarations

### PR DESCRIPTION
**Pull request by keatongreve**
See https://github.com/snesrev/zelda3/pull/21#issuecomment-1232293382

### CODE REVIEW

**Comment by yne** [comment]
Wow, you're a lifesaver !

Can I squash both this commit and mine ?

**Comment by keatongreve** [comment]
Yeah, I would imagine that looks cleaner since it will undo part of your diff where `struct` was added 👍

**Comment by yne** [comment]
Exactly, let's avoid a roundtrip

For obscure reason, I now have a linking issue with ancilla

```bash
CFLAGS=-DSDL_DISABLE_IMMINTRIN_H CC=tcc make clean_obj zelda3

rm -f ancilla.o ...
tcc -DSDL_DISABLE_IMMINTRIN_H -I/usr/include/SDL2 -D_REENTRANT   -c -o ancilla.o ancilla.c
tcc ...
tcc ancilla.o ... -o zelda3  -L/usr/lib -pthread -lSDL2


tcc: error: undefined symbol 'Ancilla_TerminateSelectInteractives'
tcc: error: undefined symbol 'AncillaAdd_BlastWall'
tcc: error: undefined symbol 'AncillaAdd_DoorDebris'
tcc: error: undefined symbol 'AncillaAdd_BushPoof'
tcc: error: undefined symbol 'GameOverText_Draw'
tcc: error: undefined symbol 'Ancilla_MoveX'
tcc: error: undefined symbol 'Ancilla_GetX'
tcc: error: undefined symbol 'ConfigureRevivalAncillae'
tcc: error: undefined symbol 'RevivalFairy_Main'
tcc: error: undefined symbol 'AddBirdTravelSomething'
tcc: error: undefined symbol 'AncillaAdd_VictorySpin'
tcc: error: undefined symbol 'Ancilla_AddAncilla'
tcc: error: undefined symbol 'AncillaAdd_CapePoof'
tcc: error: undefined symbol 'AncillaAdd_MSCutscene'
tcc: error: undefined symbol 'Ancilla_SetXY'
tcc: error: undefined symbol 'CallForDuckIndoors'
tcc: error: undefined symbol 'AncillaAdd_EtherSpell'
tcc: error: undefined symbol 'AncillaAdd_FallingPrize'
tcc: error: undefined symbol 'AncillaAdd_BombosSpell'
tcc: error: undefined symbol 'AncillaAdd_Splash'
tcc: error: undefined symbol 'AncillaAdd_DashDust_charging'
tcc: error: undefined symbol 'AncillaAdd_DashDust'
tcc: error: undefined symbol 'AncillaAdd_DashTremor'
tcc: error: undefined symbol 'AncillaAdd_Blanket'
tcc: error: undefined symbol 'AncillaAdd_Snoring'
tcc: error: undefined symbol 'AddSwordBeam'
tcc: error: undefined symbol 'AncillaAdd_SwordSwingSparkle'
tcc: error: undefined symbol 'AncillaSpawn_SwordChargeSparkle'
tcc: error: undefined symbol 'AncillaAdd_ChargedSpinAttackSparkle'
tcc: error: undefined symbol 'AncillaAdd_WallTapSpark'
tcc: error: undefined symbol 'AncillaAdd_FireRodShot'
tcc: error: undefined symbol 'AncillaAdd_IceRodShot'
tcc: error: undefined symbol 'Ancilla_AddHitStars'
tcc: error: undefined symbol 'AncillaAdd_Arrow'
tcc: error: undefined symbol 'AncillaAdd_Boomerang'
tcc: error: undefined symbol 'AncillaAdd_Bomb'
tcc: error: undefined symbol 'AncillaAdd_MagicPowder'
tcc: error: undefined symbol 'AncillaAdd_LampFlame'
tcc: error: undefined symbol 'AncillaAdd_ExplodingWeatherVane'
tcc: error: undefined symbol 'AncillaAdd_Duck_take_off'
tcc: error: undefined symbol 'AncillaAdd_QuakeSpell'
tcc: error: undefined symbol 'AncillaAdd_SpinAttackInitSpark'
tcc: error: undefined symbol 'AncillaAdd_DwarfPoof'
tcc: error: undefined symbol 'AncillaAdd_BunnyPoof'
tcc: error: undefined symbol 'AncillaAdd_SomariaBlock'
tcc: error: undefined symbol 'AncillaAdd_GraveStone'
tcc: error: undefined symbol 'Ancilla_CheckLinkCollision'
tcc: error: undefined symbol 'Ancilla_CheckTileCollision_Class2'
tcc: error: undefined symbol 'Ancilla_MoveY'
tcc: error: undefined symbol 'Ancilla_Sfx2_Pan'
tcc: error: undefined symbol 'Ancilla_Sfx3_Pan'
tcc: error: undefined symbol 'Ancilla_MoveZ'
tcc: error: undefined symbol 'Ancilla_GetY'
tcc: error: undefined symbol 'Ancilla_Main'
tcc: error: undefined symbol 'AncillaAdd_TossedPondItem'
tcc: error: undefined symbol 'AddHappinessPondRupees'
tcc: error: undefined symbol 'AncillaAdd_GTCutscene'
tcc: error: undefined symbol 'AncillaAdd_WaterfallSplash'
tcc: error: undefined symbol 'AncillaAdd_SwordChargeSparkle'
tcc: error: undefined symbol 'Ancilla_ProjectSpeedTowardsPlayer'
tcc: error: undefined symbol 'AncillaAdd_SuperBombExplosion'
```

I'll try to investigate

**Comment by yne** [comment]
Squashed into the `C99` commit : https://github.com/yne/zelda3/commits/master

Thanks !

Now I just need to rebase the upstream C++ fixes

**Pull request closed without merging**
